[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "*"
aiofiles = "*"
requests = "*"
uvloop = "*"
unidecode = "*"
lxml = "*"

[tool.poetry.group.devel]
optional = true

[tool.poetry.group.devel.dependencies]
build = "*"
mock = "*"
