[tool.poetry]
name = "argo-connectors"
version = "0.1.0"
description = ""
authors = ["Daniel Vrcic <dvrcic@srce.hr>"]
readme = "README.md"
packages = [{include = "argo_connectors"}]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "*"
aiofiles = "*"
requests = "*"
uvloop = "*"
unidecode = "*"
lxml = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
