[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
aiofiles = "*"
aiohttp = "*"
bonsai = "*"
lxml = "*"
requests = "*"
unidecode = "*"
uvloop = "*"

[tool.poetry.group.devel]
optional = true

[tool.poetry.group.devel.dependencies]
build = "*"
mock = "*"
